name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]

      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install

      - name: Run Linter, Tests and Build via Nx
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint,test,build
          all: 'true'

